### ISSUE TITLE
建议加上 --diff-filter=ACM

### ISSUE THREAD

**Issue by xcatliu** [git-hooks/contrib#2]
```
git diff-index --cached --name-only --diff-filter=ACM HEAD
```

>        --diff-filter=[(A|C|D|M|R|T|U|X|B)...[*]]
           Select only files that are Added (A), Copied (C), Deleted (D), Modified (M), Renamed (R), have their type (i.e. regular file, symlink,
           submodule, ...) changed (T), are Unmerged (U), are Unknown (X), or have had their pairing Broken (B). Any combination of the filter characters
           (including none) can be used. When * (All-or-none) is added to the combination, all paths are selected if there is any file that matches other
           criteria in the comparison; if there is no file that matches other criteria, nothing is selected.

**Comment by CatTail** [comment]
Thanks!
